export const THEMES = {
  blue: {
    card: "bg-blue-500/5 border-blue-500/20",
    iconBox: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-blue-500/10 hover:bg-blue-500/20 text-blue-700 dark:text-blue-400 border border-blue-500/20",
    buttonActive: "bg-blue-500 text-white hover:bg-blue-600 border-transparent shadow-md shadow-blue-500/20",
    input: "bg-background border border-blue-500/20 focus:border-blue-500/50 text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-blue-500/5 hover:bg-blue-500/10 text-blue-600 dark:text-blue-400",
  },
  amber: {
    card: "bg-amber-500/5 border-amber-500/20",
    iconBox: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-amber-500/10 hover:bg-amber-500/20 text-amber-700 dark:text-amber-400 border border-amber-500/20",
    buttonActive: "bg-amber-500 text-white hover:bg-amber-600 border-transparent shadow-md shadow-amber-500/20",
    input: "bg-background border border-amber-500/20 focus:border-amber-500/50 text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-amber-500/5 hover:bg-amber-500/10 text-amber-600 dark:text-amber-400",
  },
  emerald: {
    card: "bg-emerald-500/5 border-emerald-500/20",
    iconBox: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-700 dark:text-emerald-400 border border-emerald-500/20",
    buttonActive: "bg-emerald-500 text-white hover:bg-emerald-600 border-transparent shadow-md shadow-emerald-500/20",
    input: "bg-background border border-emerald-500/20 focus:border-emerald-500/50 text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-emerald-500/5 hover:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  },
  purple: {
    card: "bg-purple-500/5 border-purple-500/20",
    iconBox: "bg-purple-500/10 text-purple-600 dark:text-purple-400",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-purple-500/10 hover:bg-purple-500/20 text-purple-700 dark:text-purple-400 border border-purple-500/20",
    buttonActive: "bg-purple-500 text-white hover:bg-purple-600 border-transparent shadow-md shadow-purple-500/20",
    input: "bg-background border border-purple-500/20 focus:border-purple-500/50 text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-purple-500/5 hover:bg-purple-500/10 text-purple-600 dark:text-purple-400",
  },
  pink: {
    card: "bg-pink-500/5 border-pink-500/20",
    iconBox: "bg-pink-500/10 text-pink-600 dark:text-pink-400",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-pink-500/10 hover:bg-pink-500/20 text-pink-700 dark:text-pink-400 border border-pink-500/20",
    buttonActive: "bg-pink-500 text-white hover:bg-pink-600 border-transparent shadow-md shadow-pink-500/20",
    input: "bg-background border border-pink-500/20 focus:border-pink-500/50 text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-pink-500/5 hover:bg-pink-500/10 text-pink-600 dark:text-pink-400",
  },
  slate: {
    card: "bg-card border-border shadow-sm",
    iconBox: "bg-secondary text-muted-foreground",
    title: "text-foreground",
    textSub: "text-muted-foreground",
    buttonPrimary: "bg-secondary hover:bg-border text-foreground border border-border",
    buttonActive: "bg-primary text-primary-foreground border-transparent shadow-md",
    input: "bg-background border border-border focus:border-primary text-foreground placeholder:text-muted-foreground",
    actionButton: "bg-secondary hover:bg-border text-muted-foreground",
  }
};
